- name: Install build dependencies
  become: yes
  become_user: root
  pacman:
    name:
      - base-devel
      - ncurses
      - libssh
    state: present

- name: Install debugger dependencies
  become: yes
  become_user: root
  pacman:
    name:
      - glu
      - mesa
      - wxgtk2
      - libpng
    state: present

- name: erlang
  become_user: sgehring
  import_tasks: erlang.yaml

- name: elixir
  become_user: sgehring
  import_tasks: elixir.yaml
